const lugaresDeInteresse = {
    novaGameleira: [
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro masculino no prédio 12 - primeiro andar',
    },
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro masculino no prédio 12 - segundo andar',
    },

    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro feminino no prédio 12 - primeiro andar',
    },
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro feminino no prédio 12 - segundo andar',
    },
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Salas de informática do prédio 12',
    },
  /*  {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Salas de edificações do prédio 12',
    },*/
    {
      predio: '08',
      latitude: 33,
      longitude: 12,
      nome: 'Trincabotz',
    },
    {
      predio: '09',
      latitude: 33,
      longitude: 12,
      nome: 'Cefast',
    },
    {
      predio: 'Refeitório Escolar - Bandex',
      latitude: 33,
      longitude: 12,
      nome: 'Refeitório Escolar - bandeijão',
    },
    {
      predio: 'Refeitório Escolar - Bandex',
      latitude: 33,
      longitude: 12,
      nome: 'DCE',
    },
    {
      predio: 'Refeitório Escolar - Bandex',
      latitude: 33,
      longitude: 12,
      nome: 'Loja de utilitários e xerox',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Prédio 20',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 20 - 1° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 20 - 2° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 20 - 3° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 20 - 4° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 1° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 2° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 3° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 4° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 1° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 2° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 3° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 20 - 4° andar',
    },
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Prédio 12',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Prédio de Eletrônica - prédio de elt',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 1° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 2° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 3° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 4° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 5° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Masculino no prédio 19 - 6° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Maculino no prédio 19 - 7° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 1° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 2° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 3° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 4° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 5° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 6° andar',
    },
    {
      predio: '19',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro Feminino no prédio 19 - 7° andar',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Prédio 12',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'lanchonete',
    },
    {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Biblioteca',
    },
    /*
    {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Ciências Sociais Aplicadas',
    },
    {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Educação',
    },
        {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Engenharia Civil',
    },
        {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Engenharia Elétrica',
    },
        {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Engenharia Mecânica',
    },
    {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Fisíca',
    },
        {
      predio: 'Biblioteca',
      latitude: 33,
      longitude: 12,
      nome: 'Departamento de Matemática',
    },
    */
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Achados e perdidos',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Assistência ao aluno',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Secretaria',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Secretaria',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Fila do Intercampi',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Sala dos Professores',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Sala da coordenação',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Auditório 1 - 2° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Auditório - 1° andar',
    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Sala dos Professores',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Achados e perdidos',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Diretoria',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'DGO - laborátórios de informática',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'laboratórios de equipamentos biomédicos',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Auditório',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiros Femininos - 1° andar',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiros Femininos - 2° andar',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiros Femininos - 3° andar',
    },
    {
      predio: 'Principal',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiros Femininos - 4° andar',
    },
  {
    predio: 'Principal',
    latitude: 33,
    longitude: 12,
    nome: 'Banheiros Masculinos - 1° andar',
  },
  {
    predio: 'Principal',
    latitude: 33,
    longitude: 12,
    nome: 'Banheiros Masculinos - 2° andar',
  },
  {
    predio: 'Principal',
    latitude: 33,
    longitude: 12,
    nome: 'Banheiros Masculinos - 3° andar',
  },
  {
    predio: 'Principal',
    latitude: 33,
    longitude: 12,
    nome: 'Banheiros Masculinos - 4° andar',
  },

    
    ],
    novaSuica: [
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de fisíca - 1',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de fisíca - 2',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Arte Design e Tecnologia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciência e Tecnologia Ambiental',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciências Biólogicas',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciências Sociais e Filosofia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Educação Fisíca e Desporto',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Engenharia de Materiais',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Engenharia de Transportes',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Geociências',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de História',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Química',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Diretoria',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Carteirinha e Documentações',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Documentações para Bolsa',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Arte - 1',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Arte - 2',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Ginásio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - Ginásio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - térreo',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 1° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 2° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 3° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 4° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Vestiário feminino',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Vestiário masculino',
      },
      
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Refeitório Escolar - Bandeijão',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Grêmio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Biblioteca',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Enfermaria - Smood',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Bosque',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Auditório',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Ascefet',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Fila do intercampi',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Achados e perdidos',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Achados e perdidos - 2',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Microbiologia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Fisíco-Quimíca',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Mineralogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Inorgânica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Orgânica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Analítica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Processos Industriais',
      },
    ],
}