const lugaresDeInteresse = {
    novaGameleira: [
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro masculino no prédio 12',
    },
    {
      predio: '12',
      latitude: 33,
      longitude: 12,
      nome: 'Banheiro feminino no prédio 12',

    },
    {
      predio: '20',
      latitude: 33,
      longitude: 12,
      nome: 'Lanchonte HL',
    }
    ],
    novaSuica: [
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de fisíca - 1',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de fisíca - 2',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Arte Design e Tecnologia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciência e Tecnologia Ambiental',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciências Biólogicas',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Ciências Sociais e Filosofia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Educação Fisíca e Desporto',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Engenharia de Materiais',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Engenharia de Transportes',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Geociências',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de História',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Química',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Diretoria',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Carteirinha e Documentações',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Departamento de Linguagem e Tecnólogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Documentações para Bolsa',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Arte - 1',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Sala de Arte - 2',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Ginásio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - Ginásio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - térreo',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 1° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 2° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 3° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Banheiros - 4° andar',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Vestiário feminino',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Vestiário masculino',
      },
      
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Refeitório Escolar - Bandeijão',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Grêmio',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Biblioteca',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Smood',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Bosque',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Auditório',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Ascefet',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Fila do intercampi',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Achados e perdidos',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Achados e perdidos',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Microbiologia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Fisíco-Quimíca',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Mineralogia',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Inorgânica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Orgânica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Analítica',
      },
      {
        predio: 'principal',
        latitude: 33,
        longitude: 33,
        nome: 'Laboratório de Química - Processos Industriais',
      },
    ],
}